# Creación de las clases.

In [ ]:
class Persona:
  # Atributos
  peso = 70
  estatura = 1.75
  edad = 19

  def saludar():
    print("Hola mi nombre es Alvaro")

Persona.saludar()

Hola mi nombre es Alvaro


In [ ]:
class Persona:
  def __init__(self, nombre, apellido):
    self.nombre =nombre
    self.apellido=apellido
  def imprimirNombreCompleto(self):
    print(f"{self.nombre} {self.apellido}")
persona = Persona("JUAN", "APELLIDO")
persona.imprimirNombreCompleto()

JUAN APELLIDO


# Ejemplo de que Python solo acepta un solo constructor.
No hay polimorfismo en sus constructores.

In [ ]:
class Persona:
  def __init__(self, nombre, apellido):
    self.nombre =nombre
    self.apellido=apellido
  def __init__(self, nombre):
    self.nombre = nombre
    self.apellido = ""
  def imprimirNombreCompleto(self):
    print(f"{self.nombre} {self.apellido}")
persona = Persona("JUAN", "APELLIDO")
persona.imprimirNombreCompleto()

persona2 = Persona("RAUL")
persona2.imprimirNombreCompleto()

TypeError: ignored

In [ ]:
class Carro:
  def __init__(self):
    self.nombre =""
  @property
  def correr(self):
    print("Estoy corriendo")

  def aumentarVelocidad(self):
    print("Aumentar Velocidad")



carro = Carro()
carro.aumentarVelocidad()



Aumentar Velocidad


# Ejercicio 1: Recorrer Lisa
Un objeto que reciba una lista en el contructor y que se cree un método que permita calcular el promedio de las notas de un alumno "X", dado por el usuario.

In [ ]:
CDI = [
    {"alumno":"Luis", "nota":12},
    {"alumno":"Raul", "nota":15},
    {"alumno":"Jose","nota":16},
    {"alumno":"Luis","nota":14}
]
class Promedio:
  def __init__(self, listaAlumnos):
    self.lista = listaAlumnos
    self.promedioTotal = 0
    self.alumno=""
  def promedio(self, nombre):
    contador=0
    self.alumno = nombre
    for i in self.lista:
      if i['alumno']==self.alumno:
        self.promedioTotal+=i['nota']
        contador+=1
    self.promedioTotal = self.promedioTotal / contador
  def imprimir(self):
    print(f"El promedio del alumno {self.alumno} = {self.promedioTotal}")

promedio = Promedio(CDI)
promedio.promedio("Luis")
promedio.imprimir()

El promedio del alumno Luis = 13.0


# Ejercicio 2 : Carrito de Compras
* Opcion 1: Agregar un Producto a una list
* Opcion 2: Eliminar un Producto por el nombre
* Opcion 3: Mostrar productos.
* Opcion 4: Mostrar un solo producto por id o nombre


In [1]:
class CarritoCompras:
  def __init__(self):
    self.listaProductos=[]
    self.precioTotal = 0
    self.subtotal=0
    self.comision=0.025

  def agregarProducto(self, producto):
    self.listaProductos.append(producto)

  def eliminarProducto(self, idProducto):
    for i in self.listaProductos:
      if i['id']==idProducto:
        self.listaProductos.remove(i)

  def imprimirProductos(self):
    for llave, valor in enumerate(self.listaProductos):
      print(f"=============== Producto{llave} ===============")
      print(f"Nombre : {valor['nombre']}")
      print(f"Cantidad : {valor['cantidad']}")
      print(f"PrecioUnitario : {valor['precioUnitario']}")
      print(f"Precio Total: {valor['precioUnitario']*valor['cantidad']}")

carrito = CarritoCompras()
continua = ""
while True or continua=="Y":
  print("Bienvenidos a la tienda virtual")
  print("(1) Agregar Productos")
  print("(2) Eliminar Productos")
  print("(3) Mostrar por consola")
  operacion = int(input("¿Que operación quiere realizar?"))

  if operacion == 1:
    nombreProducto = input("Nombre del Producto : ")
    precioUnitario = float(input("Precio Unitario del Producto : "))

    cantidad = int(input("Cuantos productos son ? : "))
    precioTotal = cantidad*precioUnitario
    producto={"nombre":nombreProducto, "precioTotal":precioTotal, "precioUnitario":precioUnitario, "cantidad":cantidad}
    carrito.agregarProducto(producto)
  elif operacion==2:
    nombre=input("Nombre del Producto")
    carrito.eliminarProducto(nombre)
  elif operacion==3:
    carrito.imprimirProductos()
  continua = input("Desea realizar otra operación? (Y/n)")
  if continua != "Y":
    break



Bienvenidos a la tienda virtual
(1) Agregar Productos
(2) Eliminar Productos
(3) Mostrar por consola
¿Que operación quiere realizar?1
Nombre del Producto : Pastilla
Precio Unitario del Producto : 10
Cuantos productos son ? : 2
Desea realizar otra operación? (Y/n)N


#MISCELÁNEA : MÁS EJEMPLOS DE POO con Python

## Clase Vector
Permite crear un solo vector

In [2]:
import math

class Vector:

  def __init__(self, lista):
    self.lista = lista

  def __str__(self):
    return f"{self.lista}"

  def dot(self, vector):
    arr = []
    for i in range(len(self.lista)):
      resultado = self.lista[i] * vector.lista[i]
      arr.append(resultado)
    return sum(arr)

  def add(self, vector):
    arr = []
    for i in range(len(self.lista)):
      resultado = self.lista[i] + vector.lista[i]
      arr.append(resultado)
    return Vector(arr)

  def substract(self, vector):
    arr = []
    for i in range(len(self.lista)):
      resultado = self.lista[i] - vector.lista[i]
      arr.append(resultado)
    return Vector(arr)

  def norm(self):
    result = 0
    for i in self.lista:
      result += (i**2)
    return math.sqrt(result)

  def equals(self, vector):
    return self.lista == vector.lista

a = Vector([1,2,3])
b = Vector([2,6,3])
f = Vector([4,5,6])
c = a.add(b)
g = b.substract(a)
h = b.dot(f)

print(c)
print(g)
print(h)
print(c.equals(Vector([3,8,6])))

[3, 8, 6]
[1, 4, 0]
56
True


## Operaciones con vectores
Operaciones básicas con vectores.


In [3]:
import math

class Vector2:
    def __init__(self, array = []):
        self.array = array
        self.len = len(array)
    ## Método toString pueden ver más info en : https://realpython.com/lessons/how-and-when-use-str/
    def __str__(self):
        return ''.join(str(tuple(self.array))).replace(' ','')
    ## Suma de dos vectores
    def add(self, arr):
        return Vector([ a + b for a,b in zip(self.array, arr.array)])
    ## Resta de dos vectores
    def subtract(self,arr):
        return Vector([a-b for a,b in zip(self.array, arr.array)])
    ## Multiplicación Punto de 2 vectores
    def dot(self, arr):
        return sum([a*b for a, b in zip(self.array, arr.array)])
    ## Multiplicación de dos vectores
    def norm(self):
        return math.sqrt(sum([a**2 for a in self.array]))

    def equals(self, vector):
        return self.array == vector.array

a = Vector2([1,2,3])
b = Vector2([2,4,5])
print(a.add(b))
print(b)

[3, 6, 8]
(2,4,5)


# Numpy Introducción

In [ ]:
import numpy as np

print(np.zeros(5))
print(np.ones(7))
print(np.random)
print(np.arange(15))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
lista1=np.arange(15)
lista2=np.ones(7)
print(np.sum(lista2))
print(np.sum(lista1))
print(np.amax(lista1))
print(np.amin(lista1))
print(lista1.T)


7.0
105
14
0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
